### ISSUE TITLE
Failed at the nylas-scheduling-example-nodejs@0.1.0 watch script.

### ISSUE THREAD

**Issue by tjperry07** [nylas/scheduler-examples#4]
[2020-10-15T13_28_27_202Z-debug.log](https://github.com/nylas/scheduler-examples/files/5385232/2020-10-15T13_28_27_202Z-debug.log)
When running this app, it fails with error `Failed at the nylas-scheduling-example-nodejs@0.1.0 watch script.`. Console log below and log file attached.

```
8:28:26 AM - Starting compilation in watch mode...
[TypeScript] 
[Sass] An output directory must be specified when compiling a directory
[Sass] An output directory must be specified when compiling a directory
[Sass] internal/fs/utils.js:269
[Sass]     throw err;
[Sass]     ^
[Sass] 
[Sass] Error: ENOENT: no such file or directory, lstat 'src/public/css/main.scss'
[Sass]     at Object.lstatSync (fs.js:1007:3)
[Sass]     at Object.module.exports.parseDir (/Users/tatianaperry/Documents/scheduler-examples/node/node_modules/sass-graph/sass-graph.js:153:10)
[Sass]     at Object.watcher.reset (/Users/tatianaperry/Documents/scheduler-examples/node/node_modules/node-sass/lib/watcher.js:17:21)
[Sass]     at watch (/Users/tatianaperry/Documents/scheduler-examples/node/node_modules/node-sass/bin/node-sass:260:20)
[Sass]     at run (/Users/tatianaperry/Documents/scheduler-examples/node/node_modules/node-sass/bin/node-sass:319:5)
[Sass]     at Object.<anonymous> (/Users/tatianaperry/Documents/scheduler-examples/node/node_modules/node-sass/bin/node-sass:405:3)
[Sass]     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[Sass]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[Sass]     at Module.load (internal/modules/cjs/loader.js:985:32)
[Sass]     at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
[Sass]   errno: -2,
[Sass]   syscall: 'lstat',
[Sass]   code: 'ENOENT',
[Sass]   path: 'src/public/css/main.scss'
[Sass] }
[Sass] npm ERR! code ELIFECYCLE
[Sass] npm ERR! errno 1
[Sass] npm ERR! nylas-scheduling-example-nodejs@0.1.0 watch-sass: `node-sass -w src/public/css/main.scss dist/public/css/main.css`
[Sass] npm ERR! Exit status 1
[Sass] npm ERR! 
[Sass] npm ERR! Failed at the nylas-scheduling-example-nodejs@0.1.0 watch-sass script.
[Sass] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[Sass] 
[Sass] npm ERR! A complete log of this run can be found in:
[Sass] npm ERR!     /Users/tatianaperry/.npm/_logs/2020-10-15T13_28_26_983Z-debug.log
[Sass] npm run watch-sass exited with code 1
--> Sending SIGTERM to other processes..
[TypeScript] npm run watch-ts exited with code SIGTERM
--> Sending SIGTERM to other processes..
[Node] npm run watch-node exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nylas-scheduling-example-nodejs@0.1.0 watch: `concurrently -k -p "[{name}]" -n "Sass,TypeScript,Node" -c "yellow.bold,cyan.bold,green.bold" "npm run watch-sass" "npm run watch-ts" "npm run watch-node"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nylas-scheduling-example-nodejs@0.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tatianaperry/.npm/_logs/2020-10-15T13_28_27_202Z-debug.log
```

**Comment by tjperry07** [comment]
An update on this issue. 
By adding an empty `node/src/public/css/main.scss` and then fixing the `const redirectURI` in `base.ts` to the ngrok callback URL, you are able to authenticate, but after Google confirms the permissions, ngrok returns


```
Failed to complete tunnel connection
The connection to https://932b5e162858.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:5000.

Make sure that a web service is running on localhost:5000 and that it is a valid address.

The error encountered was: dial tcp [::1]:5000: connect: connection refused
```

Not able to get around this error.
